<template>
  <v-container style="margin-top: 40px">
    <gallery :photos="photos"></gallery>
  </v-container>
</template>

<script setup>
import Gallery from '@/components/gallery/gallery'
import {ref} from 'vue'

const photos = ref(
    [
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Living room with jacuzzi",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill.jpeg",
        "description": "Dnevna soba",
        "params": {"dimensions": {"width": 1600, "height": 720}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Villa yard",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-1-1920x1440.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-1-1920x1440.jpeg",
        "description": "Bazen",
        "params": {"dimensions": {"width": 1920, "height": 1440}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Home theatre in the living room",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-2-1.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-2-1.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 900, "height": 1200}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-2-1920x1440.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-2-1920x1440.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1440}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Swimming pool with green led at night",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-3-1.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-3-1.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 900, "height": 1200}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Swimming pool",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-3-1920x1440.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-3-1920x1440.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1440}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-4-1.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-4-1.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 900, "height": 1200}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Living room with upstairs in the background",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-4-1920x1440.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-4-1920x1440.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1440}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Sauna",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-5-1.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-5-1.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 900, "height": 1200}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Dining room",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-5-1920x1280.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-5-1920x1280.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1280}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Home theatre",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-6.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-6.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 900, "height": 1200}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Sauna inside living room",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-7-1.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-7-1.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 900, "height": 1200}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Bedroom",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-7-1920x1281.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-7-1920x1281.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1440}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-8-1.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-8-1.jpeg",
        "description": "Spa and towels",
        "params": {"dimensions": {"width": 900, "height": 1200}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Bathroom",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-8-1920x1281.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-8-1920x1281.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1440}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Living room and sauna",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-9-1.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-9-1.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 540, "height": 1200}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Bedroom",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-9-1920x1280.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-9-1920x1280.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1440}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Living room",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-10-1.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-10-1.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 900, "height": 1200}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Hall",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-10-1920x2880.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-10-1920x2880.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 2880}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Living room",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-11.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-11.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1600, "height": 720}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Living room and bar behind",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-12-1.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-12-1.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 540, "height": 1200}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Villa and fire pit",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-12-1920x1281.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-12-1920x1281.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1281}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Living room and sauna",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-13-1.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-13-1.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 540, "height": 1200}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "Hill house",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-13-1920x1281.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-13-1920x1281.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1281}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-14-1920x1280.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-14-1920x1280.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1280}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-15-1920x1438.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-15-1920x1438.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1438}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-16-1920x1438.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-16-1920x1438.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1438}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-17-1920x1280.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-17-1920x1280.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1280}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-18-1920x1280.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-18-1920x1280.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1280}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-19-1920x1281.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-19-1920x1281.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1281}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-20-1920x1280.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-20-1920x1280.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1280}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-21-1920x1281.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-21-1920x1281.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1281}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-22-1920x1280.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-22-1920x1280.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1280}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-23-1920x1440.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-23-1920x1440.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1440}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-24-1920x1440",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-24-1920x1440",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1440}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-25-1920x1440.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-25-1920x1440.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1440}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-26-1920x1440.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-26-1920x1440.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1440}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-27-1920x1440.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-27-1920x1440.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1440}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-28-1920x1440.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-28-1920x1440.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1440}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-29-1920x1440.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-29-1920x1440.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1440}},
      },
      {
        "id": "DZQ58MV6VVoMzXy2",
        "alt": "",
        "url": "/hillhouse/media/images/gallery/vila-prestige-hill-30-1920x1440.jpeg",
        "resized": "/hillhouse/media/images/gallery/resized/vila-prestige-hill-30-1920x1440.jpeg",
        "description": "",
        "params": {"dimensions": {"width": 1920, "height": 1440}},
      }
    ]
);

</script>
